# -*- coding: utf-8 -*-
"""feature_scaling_standard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/skandru/14532345aef71b1400e0bf251074eaa8/feature_scaling_standard.ipynb

Import Libraries
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

"""Load Sample House Price data"""

dataset = pd.read_csv('house_price_area.csv')

"""Separate features and target"""

features=dataset.iloc[:,1:].values
target=dataset.iloc[:,0].values

print(features)
print(target)

"""Split the data set into 80/20 20% test set and 80% training set"""

features_train,features_test,target_train,target_test=train_test_split(features,target,test_size=0.2,random_state=42)

"""Create Instance of Standard Scaler class"""

sc=StandardScaler()

"""Fit the StandardScaler on the features from the training set and transform"""

features_train = sc.fit_transform(features_train)

"""Apply the transform to the test set"""

features_test= sc.transform(features_test)

"""Print the scaled data sets both train and test sets"""

print("Scaled training set:\n", features_train)
    print("Scaled test set:\n", features_test)