# -*- coding: utf-8 -*-
"""Feature_Scaling_Normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvaZMPkEZxAkBT_NtIIJ8Sq2pTsFsXVA
"""



"""Import Libraries"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

"""Load Sample House Price data"""

dataset = pd.read_csv('house_price_area.csv')

"""Separate features and target"""

features = dataset.iloc[:,1:].values
target = dataset.iloc[:,0].values

print(features)
print(target)

"""Split the data set as train and test sets"""

features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.2, random_state=42)

""" Function for Min-Max normalization"""

def min_max_scaler(X):
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

"""Apply Min-Max scaling to training set"""

features_train = min_max_scaler(features_train)

"""Apply Min-Max scaling to the test set"""

features_test = min_max_scaler(features_test)

"""Print the normalized data sets"""

print("Normalized training set:\n", features_train)
print("Normalized test set:\n", features_test)